extends CharacterBody2D

# Generated by Sovereign Game Automation Studio (v1.3.12) - AI Behavior Tree
enum AIState { PATROL, CHASE, ATTACK, STUNNED, DEAD }

@export var max_hp: float = 100.0
@export var patrol_speed: float = 65.0
@export var chase_speed: float = 140.0
@export var detect_radius: float = 240.0
@export var attack_radius: float = 60.0

var current_hp: float
var current_state: AIState = AIState.PATROL
var target_player: Node = null
var patrol_direction: Vector2 = Vector2.RIGHT
var patrol_timer: float = 0.0

@onready var nav_agent = $NavigationAgent2D if has_node("NavigationAgent2D") else null
@onready var anim_player = $AnimationPlayer if has_node("AnimationPlayer") else null

func _ready() -> void:
	current_hp = max_hp
	target_player = get_tree().get_first_node_in_group("player")
	print("[AI Ready] VampireNoble initialized in PATROL state.")

func _physics_process(delta: float) -> void:
	if current_state == AIState.DEAD or current_state == AIState.STUNNED:
		return

	# Check target distance
	if is_instance_valid(target_player):
		var dist = global_position.distance_to(target_player.global_position)
		if dist <= attack_radius:
			change_state(AIState.ATTACK)
		elif dist <= detect_radius:
			change_state(AIState.CHASE)
		elif current_state == AIState.CHASE and dist > detect_radius * 1.3:
			change_state(AIState.PATROL)

	match current_state:
		AIState.PATROL:
			_process_patrol(delta)
		AIState.CHASE:
			_process_chase(delta)
		AIState.ATTACK:
			_process_attack(delta)

func _process_patrol(delta: float) -> void:
	patrol_timer += delta
	if patrol_timer >= 3.0:
		patrol_timer = 0.0
		patrol_direction = -patrol_direction
	velocity = patrol_direction * patrol_speed
	move_and_slide()
	if anim_player and anim_player.has_animation("walk"):
		anim_player.play("walk")

func _process_chase(delta: float) -> void:
	if not is_instance_valid(target_player):
		return
	var dir = (target_player.global_position - global_position).normalized()
	if nav_agent and not nav_agent.is_navigation_finished():
		nav_agent.target_position = target_player.global_position
		dir = (nav_agent.get_next_path_position() - global_position).normalized()
	velocity = dir * chase_speed
	move_and_slide()
	if anim_player and anim_player.has_animation("walk"):
		anim_player.play("walk")

func _process_attack(delta: float) -> void:
	velocity = Vector2.ZERO
	if anim_player and anim_player.has_animation("attack_slash") and not anim_player.is_playing():
		anim_player.play("attack_slash")

func take_damage(amount: float) -> void:
	if current_state == AIState.DEAD:
		return
	current_hp -= amount
	print("[AI Damage] VampireNoble took ", amount, " damage. HP remaining: ", current_hp)
	if current_hp <= 0:
		change_state(AIState.DEAD)
	else:
		if anim_player and anim_player.has_animation("hit"):
			anim_player.play("hit")

func change_state(new_state: AIState) -> void:
	if current_state == new_state:
		return
	current_state = new_state
	if current_state == AIState.DEAD:
		velocity = Vector2.ZERO
		if anim_player and anim_player.has_animation("death"):
			anim_player.play("death")
		await get_tree().create_timer(2.0).timeout
		queue_free()
